---

name: niri-deck-ublue
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - hhd-dev/hhd
        - avengemedia/dms
    install:
      packages:
        - hhd
        - adjustor
        - hhd-ui
        - niri
        - dms
        - matugen
        - quickshell-git
        - dms-greeter
        - greetd
        - cliphist
        - pipewire
        - wireplumber
        - pipewire-pulse
        - seatd
        - pipewire-jack-audio-connection-kit
        - distrobox
        - podman
  - type: signing
